version: "3.9"
services:
  node:
    build: ./build/node
    environment:
      - NODE_ENV=development
    working_dir: /app
    volumes:
      - ./build/node/data:/app
    networks:
      - tetris
    ports:
      - "8081:8081"

networks:
  tetris: