version: "3.9"
services:
  server:
    build: ./build/server
    environment:
      - NODE_ENV=development
    working_dir: /app
    volumes:
      - ./data/server:/app
    networks:
      - tetris
    ports:
      - "8081:8081"

networks:
  tetris: