version: "3.9"

services:

  server:
    build: ./dockerbuild/server

    ports:
      - "8000:4173"
      - "8001:5173"
      - "8002:3004"

    volumes:
      - ./server:/app
      - ./dist:/app/dist

    networks:
      - tetris

    environment:
      HOST: ${HOST}
      PORT: ${PORT}
      # - NODE_ENV=development

    working_dir: /app


  client:
    build: ./dockerbuild/client

    ports:
      - "8080:5173"
      # - "3004:3004"

    volumes:
      - ./client:/app
      - ./dist:/dist

    networks:
      - tetris

    # environment:
    #   - NODE_ENV=development

    working_dir: /app

networks:
  tetris:

volumes:
  pnpmstore: