services:
  frontend:
    build: ./build/frontend
    restart: "no"

    environment:
      - NODE_ENV=development
      
    volumes:
      # - ./data/frontend:/frontend
      - ./data/frontend/public:/frontend/public
      - ./data/frontend/src:/frontend/src
      - ./data/frontend/.eslintrc.cjs:/frontend/.eslintrc.cjs
      - ./data/frontend/index.html:/frontend/index.html
      - ./data/frontend/package.json:/frontend/package.json
      - ./data/frontend/pnpm-lock.yaml:/frontend/pnpm-lock.yaml
      - ./data/frontend/vite.config.js:/frontend/vite.config.js

    stdin_open:  true # docker run -i
    tty: true        # docker run -t

    networks:
      - tetris

    ports:
      - "${PORT_FRONT}:5173"


  backend:
    build: ./build/backend
    restart: "no"

    environment:
      - NODE_ENV=development

    stdin_open:  true # docker run -i
    tty: true        # docker run -t

    volumes:
      - ./data/backend:/backend
