services:
  server:
    build: ./build/server
    environment:
      # - NODE_ENV=production
      - NODE_ENV=development
    volumes:
      - ./data/server:/server
    networks:
      - tetris
    ports:
      - "8081:8081"
      - "3000:3000"

networks:
  tetris: